version: "3.7"
services:
  agent:
    image: portainer/agent:latest
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 256M
        reservations:
          cpus: "0.08"
          memory: 128M
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer:latest
    # https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55
    # create password: docker run --rm httpd:2.4-alpine htpasswd -nbB admin 'your_password' | cut -d ":" -f 2
    #  Add a $ infront of any $ in the output from above
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password-file /portainer_password
    # ports:
    #   - "9000:9000"
    volumes:
      - portainer_data:/data
      - /portainer_password:/portainer_password
    networks:
      - agent_network
      - app-net
      - traefik
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 256M
        reservations:
          cpus: "0.08"
          memory: 128M
      replicas: 1
      placement:
        constraints:
         - node.labels.type == initial_master
      labels:
        - traefik.frontend.rule=Host:${ENVIRONMENT}-portainer.${DOMAIN}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.docker.network=traefik
        - traefik.http.frontend.entryPoints=http
    ports:
      - target: 9000
        published: 9000
        mode: host

networks:
  agent_network:
    driver: overlay
    attachable: true
  app-net:
    external: true
  traefik:
    external: true


volumes:
  portainer_data:
    # driver: "cloudstor:aws"
    # driver_opts:
    #   ebstype: gp2
    #   size: 25
    #   iops: 1000
    #   backing: relocatable
